---
require:
  - rubocop-rspec

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: leading
  Enabled: true

Layout/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Lint/LiteralInInterpolation:
  Description: 'Avoid interpolating literals in strings'
  AutoCorrect: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/MethodLength:
  Max: 12

Naming/FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  EnforcedStyle: nested
  Enabled: true

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-i'
  Enabled: false # Only available in Ruby 2.0+

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
  Enabled: true
