version: 2.1
orbs:
  ruby: circleci/ruby@1.1
jobs:
  check_and_test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run static code analysis
          command: bundle exec rubocop
      - run:
          name: Run tests
          command: bundle exec rspec
workflows:
  version: 2
  test:
    jobs:
      - check_and_test:
          # cribbed from http://mikebian.co/running-tests-against-multiple-ruby-versions-using-circleci/
          matrix:
            parameters:
              ruby-version: ["2.6", "2.7", "3.0", "3.1"]
